# This is a basic workflow to help you get started with Actions

name: Deploy First-Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   test-first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a single command using the runner shell
      - name: Print goodbye
        run: echo "done -Bye!!"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
   deploy: 
     
     runs-on: ubuntu-latest
     steps: 
       - name: Get code
         uses: actions/checkout@v4
       - name: install NodeJS
         uses: actions/setup-node@v4
         with:
           node-version: 18
       - name: build project
         uses: pavi2410/html-preview-action@v2
       - name: Deploy
         run: echo "Deploying ...."
        
    
